#!/bin/sh

case "$1" in
start)
  ip addr add 127.0.0.1/8 label lo dev lo
  ip link set lo up

  cat /etc/hostname >/proc/sys/kernel/hostname

  ;;
stop) ;;

restart | reload)
  "$0" stop
  "$0" start
  ;;
*)
  echo $"Usage: $0 {start|stop|restart}"
  exit 1
  ;;
esac

exit $?
